### ISSUE TITLE
Ada Ada Ada style is not dimension-less

### ISSUE THREAD

**Issue by camilleroux** [camilleroux/fxhash-bridge#81]
Hi @ada-ada-ada-art 

Your background changes a lot when I'm resizing the image: (different sizes, same hash)
![image](https://user-images.githubusercontent.com/25977/154857030-1af566b6-3664-4642-a763-3aed83565d3f.png)
![image](https://user-images.githubusercontent.com/25977/154857042-a0b9fb9b-77d2-4f06-a9f4-bbb466b2834d.png)
![image](https://user-images.githubusercontent.com/25977/154857056-e0f0683f-3527-4dc0-89a0-9718bbf7fed6.png)

**Comment by ada-ada-ada-art** [comment]
@camilleroux 
I'm aware of this, but I mentioned in my comment in #57 that it's really difficult for me to control the glitchy background effects.

I have to lose the effect in order to make it look 100% the same on all sizes due to the way the glitches are produced. Less fun, but I guess it's my only choice, if the dimension-less thing is super important to you. 

There's a fix ready in #87.

**Comment by camilleroux** [comment]
Ho sorry, I missed that comment...
It's much better if styles are dimension-less. But I liked your glitchy background. If you want to keep it, revert and I'll do an exception for you :)
