### ISSUE TITLE
mandyBrigwell style is not dimension-less #2

### ISSUE THREAD

**Issue by AqwUnderscoreZert** [camilleroux/fxhash-bridge#99]
Hi @mandyBrigwell

After checking, once again your project, it still shows the different tiles form problem... It looks like an issue with some rounding (using int() or floor()). 

![image](https://user-images.githubusercontent.com/98602680/154870926-d0c2c70f-8c63-47ab-90e1-31d2cdeedfe8.png)

**Comment by mandyBrigwell** [comment]
I'm afraid I can't see where the issue lies—it's got me completely mystified. I don't use int() or floor(), so that's not an issue.

It happens when the dimension s changes from being the width to the height, but I can't find anywhere in the code that would cause this.

**Comment by mandyBrigwell** [comment]
Issue resolved and pushed.

**Comment by mandyBrigwell** [comment]
I figured out that because my initial graphics layer was calling random() a number of times dependent on the size of the screen, the random numbers when it got to the main loop were not the same. Took me way to long to work that out!

I could replace the initial random calls with noise, but I think I prefer it without them.
